# Generated by Django 4.0 on 2023-07-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
